=== alexrob123/DSS2026/exercices/games.dtd
<!ELEMENT matchs (match+)>

<!ELEMENT match (equipe1, equipe2, domicile, buts?, cartons?)>

<!ELEMENT equipe1 (#PCDATA)>
<!ELEMENT equipe2 (#PCDATA)>
<!ELEMENT domicile (#PCDATA)>

<!ELEMENT buts (but*)>
<!ELEMENT but (joueur, minute, penalty?)>
<!ELEMENT joueur (#PCDATA)>
<!ELEMENT minute (#PCDATA)>
<!ELEMENT penalty (#PCDATA)>

<!ELEMENT cartons (carton*)>
<!ELEMENT carton (joueur, type)>
<!ELEMENT type (#PCDATA)>

=== alexrob123/DSS2026/exercices/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matchs SYSTEM "games.dtd">

<matchs>
    <match>
        <equipe1>Paris Saint-Germain</equipe1>
        <equipe2>Olympique Lyonnais</equipe2>
        <domicile>Paris Saint-Germain</domicile>

        <buts>
            <but>
                <joueur>Kylian Mbappé</joueur>
                <minute>12</minute>
            </but>
            <but>
                <joueur>Lionel Messi</joueur>
                <minute>45</minute>
                <penalty>oui</penalty>
            </but>
            <but>
                <joueur>Memphis Depay</joueur>
                <minute>78</minute>
            </but>
        </buts>

        <cartons>
            <carton>
                <joueur>Marquinhos</joueur>
                <type>jaune</type>
            </carton>
            <carton>
                <joueur>Lucas Paquetá</joueur>
                <type>rouge</type>
            </carton>
        </cartons>
    </match>

    <match>
        <equipe1>Real Madrid</equipe1>
        <equipe2>FC Barcelone</equipe2>
        <domicile>Real Madrid</domicile>

        <buts>
            <but>
                <joueur>Karim Benzema</joueur>
                <minute>22</minute>
            </but>
        </buts>

        <cartons>
            <carton>
                <joueur>Sergio Ramos</joueur>
                <type>jaune</type>
            </carton>
        </cartons>
    </match>
</matchs>
